import { createAccessControl } from 'better-auth/plugins/access';
import { defaultStatements } from 'better-auth/plugins/organization/access';

const statements = {
  ...defaultStatements,
  customer: ['create', 'read', 'update', 'delete'],
  project: ['create', 'read', 'update', 'delete', 'share'],
  design: ['create', 'read', 'update', 'approve'],
  schedule: ['create', 'read', 'update', 'approve'],
  finance: ['create', 'read', 'update', 'approve'],
  construction: ['create', 'read', 'update', 'approve'],
  task: ['create', 'read', 'update', 'delete'],
  file: ['create', 'read', 'update', 'delete'],
  ai: ['create', 'read', 'cancel', 'retry'],
  audit: ['read'],
  billing: ['read', 'update'],
} as const;

export const studioAccess = createAccessControl(statements);

const allStudioPermissions = {
  organization: ['update', 'delete'],
  member: ['create', 'update', 'delete'],
  invitation: ['create', 'cancel'],
  team: ['create', 'update', 'delete'],
  ac: ['create', 'read', 'update', 'delete'],
  customer: ['create', 'read', 'update', 'delete'],
  project: ['create', 'read', 'update', 'delete', 'share'],
  design: ['create', 'read', 'update', 'approve'],
  schedule: ['create', 'read', 'update', 'approve'],
  finance: ['create', 'read', 'update', 'approve'],
  construction: ['create', 'read', 'update', 'approve'],
  task: ['create', 'read', 'update', 'delete'],
  file: ['create', 'read', 'update', 'delete'],
  ai: ['create', 'read', 'cancel', 'retry'],
  audit: ['read'],
  billing: ['read', 'update'],
} as const;

export const studioRoles = {
  owner: studioAccess.newRole(allStudioPermissions),
  admin: studioAccess.newRole({ ...allStudioPermissions, organization: ['update'] }),
  lead_designer: studioAccess.newRole({
    organization: [],
    member: [],
    invitation: [],
    team: [],
    ac: ['read'],
    customer: ['create', 'read', 'update'],
    project: ['create', 'read', 'update', 'share'],
    design: ['create', 'read', 'update', 'approve'],
    schedule: ['create', 'read', 'update', 'approve'],
    finance: ['read'],
    construction: ['create', 'read', 'update', 'approve'],
    task: ['create', 'read', 'update', 'delete'],
    file: ['create', 'read', 'update', 'delete'],
    ai: ['create', 'read', 'cancel', 'retry'],
    audit: [],
    billing: [],
  }),
  designer: studioAccess.newRole({
    organization: [],
    member: [],
    invitation: [],
    team: [],
    ac: ['read'],
    customer: ['read'],
    project: ['read', 'update'],
    design: ['create', 'read', 'update'],
    schedule: ['create', 'read', 'update'],
    finance: [],
    construction: ['read'],
    task: ['create', 'read', 'update'],
    file: ['create', 'read', 'update'],
    ai: ['create', 'read', 'cancel', 'retry'],
    audit: [],
    billing: [],
  }),
  procurement: studioAccess.newRole({
    organization: [],
    member: [],
    invitation: [],
    team: [],
    ac: ['read'],
    customer: ['read'],
    project: ['read'],
    design: ['read'],
    schedule: ['create', 'read', 'update', 'approve'],
    finance: ['create', 'read', 'update'],
    construction: ['read', 'update'],
    task: ['create', 'read', 'update'],
    file: ['create', 'read', 'update'],
    ai: ['create', 'read'],
    audit: [],
    billing: [],
  }),
  finance: studioAccess.newRole({
    organization: [],
    member: [],
    invitation: [],
    team: [],
    ac: ['read'],
    customer: ['read'],
    project: ['read'],
    design: ['read'],
    schedule: ['read'],
    finance: ['create', 'read', 'update', 'approve'],
    construction: ['read'],
    task: ['create', 'read', 'update'],
    file: ['create', 'read', 'update'],
    ai: ['read'],
    audit: ['read'],
    billing: ['read', 'update'],
  }),
  assistant: studioAccess.newRole({
    organization: [],
    member: [],
    invitation: [],
    team: [],
    ac: ['read'],
    customer: ['create', 'read', 'update'],
    project: ['create', 'read', 'update'],
    design: ['create', 'read', 'update'],
    schedule: ['create', 'read', 'update'],
    finance: ['read'],
    construction: ['create', 'read', 'update'],
    task: ['create', 'read', 'update'],
    file: ['create', 'read', 'update'],
    ai: ['create', 'read'],
    audit: [],
    billing: [],
  }),
  viewer: studioAccess.newRole({
    organization: [],
    member: [],
    invitation: [],
    team: [],
    ac: ['read'],
    customer: ['read'],
    project: ['read'],
    design: ['read'],
    schedule: ['read'],
    finance: [],
    construction: ['read'],
    task: ['read'],
    file: ['read'],
    ai: ['read'],
    audit: [],
    billing: [],
  }),
};
